# Generated by Django 4.1.3 on 2022-12-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_important'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='Title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='Memo',
        ),
        migrations.AddField(
            model_name='todo',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
