# Generated by Django 4.1.3 on 2022-12-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_rename_title_todo_title_remove_todo_memo_todo_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
